### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by mgcth** [Ingenjorsarbete-For-Klimatet/smhi#9]
@docNord , think we should probably name this oficially as `ifk-smhi` or `smhi-ifk` as `smhi` most likely is taken and would be nice if future packages referenced `ifk` somehow.

**Comment by docNord** [comment]
I concur. Naming our packages with either a prefix or a suffix makes a lot of sense. Perhaps the prefix variant is more clear? When you put package calls below each other, the ifk- will then be aligned so that it will be easy to read the relevant parts of the package names, eg:

from ifk-smhi.strang import Strang
from ifk-wmo.oscar import Oscar
from ifk- etc

**Comment by mgcth** [comment]
Minor annoyance is that in python we would have to write with an underscore, i.e. `ifk_smhi`, but the package would be named `ifk-smhi`.

**Comment by docNord** [comment]
can't we just use ifk_smhi as the package name as well?

**Comment by mgcth** [comment]
I'm leaning towards naming the repo and package `ifk-smhi` and the module `ifksmhi` or just `smhi`. Looks like some other python packages have chosen this like: https://github.com/scikit-learn/scikit-learn

**Comment by mgcth** [comment]
Decided on `ifk-smhi` for the package and `smhi` for the module then.

**Comment by docNord** [comment]
Good decision!
